#!/bin/bash
# ToGMAL MCP Server - Quick Run Commands

echo "ToGMAL MCP Server - Quick Commands"
echo "===================================="
echo ""
echo "Choose an option:"
echo ""
echo "1. Run test examples (shows 9 detection scenarios)"
echo "   source .venv/bin/activate && python test_examples.py"
echo ""
echo "2. Open MCP Inspector (web UI for testing)"
echo "   source .venv/bin/activate && npx @modelcontextprotocol/inspector python togmal_mcp.py"
echo ""
echo "3. Test MCP client (programmatic access)"
echo "   source .venv/bin/activate && python test_client.py"
echo ""
echo "4. Verify server syntax"
echo "   source .venv/bin/activate && python -m py_compile togmal_mcp.py"
echo ""
echo "5. For Claude Desktop: Copy config"
echo "   cp claude_desktop_config.json ~/Library/Application\ Support/Claude/claude_desktop_config.json"
echo ""
